---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Simulated data example

```{r}
library(tidyverse)
library(pracma)
library(roperators)
library(MASS)
library(caret)

cov_mat = function(n, a){
  mat1 = exp(log(a) * toeplitz(seq(0, n-1)))
  return(mat1)
}
```

```{r}
t = seq(5, 14, 1)
increasing_part = 7.5 + 2.5*sin(pi*t/10 - pi)
flat_part = rep(5, 10)
beta = c(flat_part, increasing_part, 5 + flat_part)
plot(beta)
```

```{r}
n = 20
p = 30
set.seed(123)
X = mvrnorm(n, mu = rep(0, p), Sigma = cov_mat(p, 0.8))
y = X %*% beta + rnorm(n, mean = 0, sd = 1)
```

```{r}
newx = mvrnorm(10, mu = rep(0, p), Sigma = cov_mat(p, 0.8))
newy = newx %*% beta + rnorm(10, mean = 0, sd = 1)
```

```{r}
D = matrix(0, nrow = p, ncol = p)  
diag(D) = 1
diag(D[, -1]) = -1
D = D[1:p-1, 1:p]
```



```{r}
setwd("~/Desktop/network_regularization/network_regularisation")

source("src_R/cd_solver_R.R")
source("src_R/ip_solver_R.R")
source("src_R/admm_solver_R.R")
source("src_R/penalties.R")
source("src_R/losses.R")
library(caret)

genglm <- function(x, y, D, family = c("gaussian", "binomial", "poisson"),
                   lambda1 = 1.,
                   lambda2 = 1.,
                   standardize = TRUE,
                   solver = c("ECOS", "IP", "ADMM", "CD"),
                   intercept = TRUE){
  
  n = nrow(x)
  p = ncol(x)
  
  if(family != "gaussian" || is.null(solver)){
    beta1 = Variable(p)
    if(family == "binomial"){
        if (solver == "ECOS"){
          prob1 = Problem(Minimize(logit_loss(x, y, beta1)+gen_penalty(beta1,lambda1,lambda2,D)))
        }
    }
    if (family == "poisson"){
      if (solver == "ECOS"){
        prob1 = Problem(Minimize(poisson_loss(x, y, beta1)+gen_penalty(beta1,lambda1,lambda2,D)))
      }
    }
    if(family == "gaussian"){
      prob1 = Problem(Minimize(l2_loss(x, y, beta1)+gen_penalty(beta1,lambda1,lambda2,D)))
    }
    CVXR_solution <- solve(prob1)
    hat_beta = CVXR_solution$getValue(beta1)
    #return(hat_beta)
  }
  else if(solver == "IP" && family == "gaussian"){
    hat_beta = ip_solver(x, y, D, lambda1, lambda2, mu = 1.5, eps = 1e-4, max_it = 10000)
    #return(hat_beta)
  }
  else if(solver == "ADMM" && family == "gaussian"){
    hat_beta = admm_solver(x, y, D, lambda1, lambda2, rho = 1, eps = 1e-3, max_it = 50000)
    #return(hat_beta)
  }
  else if(solver == "CD" && family == "gaussian"){
    hat_beta  = cgd_solver(x ,y, D, lambda1, lambda2, eps = 1e-4, max_it = 10000)
    #return(hat_beta)
  }
  else if (solver == "ECOS" && family == "gaussian"){
      beta1 = Variable(p)
      prob1 = Problem(Minimize(l2_loss(x, y, beta1) + gen_penalty(beta1, lambda1,lambda2,D)))
      CVXR_solution <- solve(prob1)
      hat_beta  = CVXR_solution$getValue(beta1)
      #return(hat_beta)
  }
  else{
        print("Not implemented yet")
        #return(NA)
  }
  fit <- list(hat_beta = hat_beta, lambda1 = lambda1, lambda2 = lambda2, family = family, solver = solver)
  attr(fit, "class") <- "genglm"
  fit
}

```



```{r}
predict.genglm <- function(object,newx,type=c("link","response"),s=c('lambda.min','lambda.1se'),
                                                                     exact=FALSE){
  
  # gaussian: return fitted values
  # binomial: return linear predictors if type==link, return fitted probabilities if type==response
  # poisson: return linear predictors if type==link, return fitted mean if type==response
  
  if(class(object)=='genglm'){
    if(type == "link"){
      return(newx %*% object$hat_beta)
    }
    else if(type == "response"){
      if(object$family == "gaussian"){
        return(newx %*% object$hat_beta)
      }
      else if(object$family == "binomial"){
        return(exp(newx %*% object$hat_beta)/(1+exp(newx %*% object$hat_beta)))
      }
      else if(object$family == "poisson"){
        return(exp(newx %*% object$hat_beta))
      }
    }
    return(NA)
  }
  else if(class(object)=='cv.genglm'){
    if(s=='lambda.min'){
      if(type == "link"){
        return(newx %*% object$hat_beta.min)
      }
      else if(type == "response"){
        if(object$family == "gaussian"){
          return(newx %*% object$hat_beta.min)
        }
        else if(object$family == "binomial"){
          return(exp(newx %*% object$hat_beta.min)/(1+exp(newx %*% object$hat_beta.min)))
        }
        else if(object$family == "poisson"){
          return(exp(newx %*% object$hat_beta.min))
        }
      }
      return(NA)
    }
  }
}
```

```{r}
coef.genglm <- function(object, s=c('lambda.1se','lambda.min')){
  if(class(object)=='genglm'){
    print('hi1')
    return(object$hat_beta)
  }
  else if(class(object)=='cv.genglm'){
    if(s=='lambda.min'){
      print('hi')
      return(object$hat_beta.min)
    }
  }
}
```

```{r}
# returns mean squared error for one fold 

folds_cv = function(fold, x, y, D, family, l1, l2, solver){
  train_x = x[-fold,]
  test_x = x[fold,]
  
  train_y = matrix(y[-fold,])
  test_y = matrix(y[fold,])
  
  model = genglm(train_x,train_y,D,family=family,l1,l2,solver=solver)
  fitted_y = predict.genglm(model, test_x,type="response")
  fold_score = mean((test_y-fitted_y)^2)
  return(fold_score)
}
```

```{r}
# returns average mean squared error across folds for one lambda1 & lambda2 combination
param_cv = function(lambda_row, x, y, D, folds, family, solver){
  l1 = lambda_row[1]
  l2 = lambda_row[2]

  param_score = mean(unlist(lapply(folds, folds_cv, x=x, y=y, D=D, family=family, solver=solver, l1=l1, l2=l2)))
  return(param_score)
}
```


```{r}
vectorized.cv.genglm = function(x,
                      y,
                      D,
                      type.measure = c("deviance","mean_squared_error"),
                      family = c("gaussian","binomial","poisson"),
                      solver = c("ECOS", "IP", "ADMM", "CD"),
                      lambda1 = 10^seq(-3,2,1), lambda2 = 10^seq(-3,2,1),
                      n_folds=2){
  N <- nrow(x)
  folds = createFolds(1:N,k=n_folds)
  
  lambdas = expand.grid(lambda1,lambda2)
  colnames(lambdas) = c('l1','l2')
  cv_scores = apply(lambdas, 1, param_cv, x=x,y=y,D=D,folds,family=family,solver=solver)
  
  lambda1.min = lambdas[which.min(cv_scores),]$l1
  lambda2.min = lambdas[which.min(cv_scores),]$l2
  
  model.min = genglm(x=x, y=y,
                     D=D,family=family,
                     lambda1=lambda1.min,
                     lambda2=lambda2.min, solver=solver,
                     standardize = TRUE)
  hat_beta.min = model.min$hat_beta
  
  
  cv <- list(lambda1.min = lambda1.min, lambda2.min = lambda2.min, 
             family = family, solver = solver,
             hat_beta.min = hat_beta.min)
  attr(cv, "class") <- "cv.genglm"
  cv
}
```

```{r}
cv.genglm <- function(x,
                      y,
                      D,
                      type.measure = c("deviance","mean_squared_error"),
                      family = c("gaussian","binomial","poisson"),
                      solver = c("ECOS", "IP", "ADMM", "CD"),
                      lambda1 = 10^seq(-3,2,1), lambda2 = 10^seq(-3,2,1),
                      n_folds=2){
  # lambda1 and lambda2 are lists of the candidate values for lambda1 and lambda2
  #model.cv = cv.genglm(X,y,D,family='gaussian',solver='CD')
  print(c(family, solver))
  N <- nrow(x)
  folds = createFolds(1:N,k=n_folds)
  
  lambdas = expand.grid(lambda1,lambda2)
  colnames(lambdas) = c('l1','l2')
  cv_scores = c()
  
  for(i in 1:nrow(lambdas)){
    l1 = lambdas[i,]$l1
    l2 = lambdas[i,]$l2
    
    fold_scores = c()
    for(fold in folds){
      train_x = x[-fold,]
      test_x = x[fold,]
      
      train_y = matrix(y[-fold,])
      test_y = matrix(y[fold,])
      
      model = genglm(x=train_x, y=train_y,
                     D=D,family=family,
                     lambda1=l1,
                     lambda2=l2, solver=solver,
                     standardize = TRUE)
      fitted_y = predict.genglm(model, test_x,type="response")
      
      # if(type.measure == "deviance"){
      #   
      # }
      fold_scores = c(fold_scores, mean((test_y-fitted_y)^2))
    }
    cv_scores = c(cv_scores, mean(fold_scores))
  }
  
  lambda1.min = lambdas[which.min(cv_scores),]$l1
  lambda2.min = lambdas[which.min(cv_scores),]$l2
  
  # lambda1.1se
  # lambda2.1se
  
  cv <- list(lambda1.min = lambda1.min, lambda2.min = lambda2.min, family = family, solver = solver)
  attr(cv, "class") <- "cv.genglm"
  cv
}
```





```{r}
model = genglm(X,y,D,family="gaussian",solver="CD")
plot(model$hat_beta)
```

```{r}
model.cv = cv.genglm(X,y,D,family='gaussian',solver='CD')
```

```{r}
model.vectorized.cv = vectorized.cv.genglm(X,y,D,family='gaussian',solver='CD')
```

```{r}
coef.genglm(model.vectorized.cv, s='lambda.min')
```

```{r}
predict.genglm(model.vectorized.cv,newx,type='response',s='lambda.min')
```


```{r}
library(glmnet)
```

```{r}
data(QuickStartExample)
x <- QuickStartExample$x
y <- QuickStartExample$y
```


```{r}
fit <- cv.glmnet(x, y)
```



